package com.mahmoudelgohary.ecommerce.dataproviders;

import com.mahmoudelgohary.ecommerce.util.ApisRequestHelper;
import org.testng.annotations.DataProvider;

import static org.apache.http.HttpStatus.SC_OK;
import static org.apache.http.HttpStatus.SC_UNAUTHORIZED;

public class LoginDataProvider {

    // This data provider generates test cases for different login credentials, including valid admin and user credentials, as well as invalid credentials.
    // Each test case consists of a LoginRequest object and the expected HTTP status code for the login attempt.
    // The parallel = true attribute allows TestNG to run the tests generated by this data provider in parallel, which can help speed up the execution of tests when there are many test cases.
    @DataProvider(name = "LoginData", parallel = true)
    public Object[][] provideLoginData() {
        return new Object[][]{
                {ApisRequestHelper.getAdminLoginRequest(), SC_OK},
                {ApisRequestHelper.getUserLoginRequest(), SC_OK},
                {ApisRequestHelper.getInvalidUserLoginRequest(), SC_UNAUTHORIZED}
        };
    }


}
