package com.mahmoudelgohary.ecommerce.dataproviders;

import com.mahmoudelgohary.ecommerce.constants.InvalidType;
import com.mahmoudelgohary.ecommerce.util.ApisRequestHelper;
import org.testng.annotations.DataProvider;

public class RegisterDataProviders {

    // This data provider generates test cases for valid registration data. It creates multiple instances of RegisterRequest using the ApisRequestHelper.
    // The number of test cases generated can be adjusted by changing the value of the numberOfTests variable. Each test case will contain a valid RegisterRequest object.
    // The parallel = true attribute allows TestNG to run the tests generated by this data provider in parallel, which can help speed up the execution of tests when there are many test cases.
    @DataProvider(name = "validRegistrationData", parallel = true)
    public Object[][] validRegistrationDataProvider() {
        // Provide multiple sets of RegisterRequest data for testing
        int numberOfTests = 3; // You can adjust this number to generate more or fewer test cases
        Object[][] data = new Object[numberOfTests][1];

        for (int i = 0; i < numberOfTests; i++) {
            data[i][0] = ApisRequestHelper.getValidRegisterRequest();
        }
        return data;
    }

    // This data provider generates test cases for various types of invalid registration data based on the InvalidType enum.
    // It creates a test case for each type of invalid input defined in the InvalidType enum by calling the getInvalidRegisterRequest method from the ApisRequestHelper.
    // The test cases generated by this data provider will cover scenarios such as missing fields, invalid email formats, duplicate emails, invalid data types, and short passwords.
    // The parallel = true attribute allows TestNG to run the tests generated by this data provider in parallel, which can help speed up the execution of tests when there are many test cases.
    @DataProvider(name = "inValidRegistrationData", parallel = true)
    public Object[][] inValidRegistrationDataProvider() {
        InvalidType[] types = InvalidType.values();
        int numberOfTests = types.length; // Generate one test case for each type of invalid input defined in the InvalidType enum
        Object[][] data = new Object[numberOfTests][1];

        for (int i = 0; i < numberOfTests; i++) {
            data[i][0] = ApisRequestHelper.getInvalidRegisterRequest(types[i]);
        }
        return data;
    }
}
